# 随机数

## 一次生成一个数

In [1]:
import random
random.seed(3) # 设置随机数的“种子数”

In [6]:
# 生成一个[1, 100]之间的随机整数
import random
random.seed(3)
random.randint(1, 100)

31

In [13]:
# 生成一个[-10, 10]之间的随机浮点数
random.seed(3)
random.uniform(-10, 10)

-5.240707458162173

In [14]:
# 四舍五入，保留两位小数
random.seed(3)
round(random.uniform(-10, 10), 2)

-5.24

## 一次生成一个随机数组

In [16]:
import numpy as np
# 第一步： 定义一个随机变量的生成器
rand = np.random.RandomState(32) # 32 为随机数种子数
# 第二步： 选择生成器提供的具体方法
x = rand.randint(0, 10, (3, 6)) # (3, 6)为目标数组的形状
x

array([[7, 5, 6, 8, 3, 7],
       [9, 3, 5, 9, 4, 1],
       [3, 1, 2, 3, 8, 2]])

In [19]:
# 均匀分布
import numpy as np
rand = np.random.RandomState(1)
x = rand.rand(5) * 10
x

array([4.17022005e+00, 7.20324493e+00, 1.14374817e-03, 3.02332573e+00,
       1.46755891e+00])

In [21]:
# 正态分布
import numpy as np
rand = np.random.RandomState(1)
y = rand.randn(5) + 5
y

array([6.62434536, 4.38824359, 4.47182825, 3.92703138, 5.86540763])

In [24]:
# 生成等距数组
x = np.linspace(0, 10, 20) # [0-10]  20个元素
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])