# 实验3 K-L变换算法

In [1]:
import numpy as np

实验样本

In [2]:
x = [[-5, -5],
    [-5, -4],
    [-4, -5],
    [-5, -6],
    [-6, -5],
    [5, 5],
    [5, 6],
    [6, 5],
    [5, 4],
    [4, 5]]
d = 2
n = 10

## （1）计算样本向量的均值

In [3]:
def get_u(x, d, n):
    """
    计算样本向量的均值
    x 样本数组
    d 样本维度
    n 样本个数
    return 均值
    """
    SUM = np.mat(np.zeros(d)).T
    for i in range(n):
        SUM[0,0] += x[i][0]
        SUM[1,0] += x[i][1]
    return SUM/n

In [4]:
u = get_u(x, d, n)
print("样本均值向量为：\n", u)

样本均值向量为：
 [[0.]
 [0.]]


##       计算协方差矩阵

In [5]:
def get_C(x, n, u):
    """
    计算协方差矩阵
    x 样本数组
    return 协方差矩阵
    """
    X = np.mat(x).T
   
    return np.cov(X)

In [6]:
C_x = get_C(x, n, u)
print("协方差矩阵为：\n", C_x)

协方差矩阵为：
 [[28.22222222 27.77777778]
 [27.77777778 28.22222222]]


## （2）计算特征值和特征向量

In [7]:
eva, fec = np.linalg.eig(C_x)
print("特征值为：\n", eva, "\n特征向量为：\n", fec)

特征值为：
 [56.          0.44444444] 
特征向量为：
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
print("上述特征值排序后的数组下标为：", np.argsort(eva))

上述特征值排序后的数组下标为： [1 0]


In [9]:
U_new = np.mat([fec[0, 0], fec[1, 0]]).T
print("新的变换阵U_new:\n", U_new)

新的变换阵U_new:
 [[0.70710678]
 [0.70710678]]


## 求解新的一维样本

In [10]:
for i in range(n):
    y = U_new.T * np.mat(x[i]).T
    print("第", i, "个样本K-L变换后的结果：", y)

第 0 个样本K-L变换后的结果： [[-7.07106781]]
第 1 个样本K-L变换后的结果： [[-6.36396103]]
第 2 个样本K-L变换后的结果： [[-6.36396103]]
第 3 个样本K-L变换后的结果： [[-7.77817459]]
第 4 个样本K-L变换后的结果： [[-7.77817459]]
第 5 个样本K-L变换后的结果： [[7.07106781]]
第 6 个样本K-L变换后的结果： [[7.77817459]]
第 7 个样本K-L变换后的结果： [[7.77817459]]
第 8 个样本K-L变换后的结果： [[6.36396103]]
第 9 个样本K-L变换后的结果： [[6.36396103]]
